dist: trusty

sudo: required

language: go

go:
  - 1.10.x

env:
  - DB=mysql DB_VERSION=5.7
  - DB=mysql DB_VERSION=8.0

services:
  - docker

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - sudo service mysql stop
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT=localhost:3306
  - export MYSQL_PASSWORD=tests
  - sudo docker run -e MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD} -d -p 3306:3306 ${DB}:${DB_VERSION}
  - sleep 10
  - sudo docker ps
  - mysql -hlocalhost --protocol=tcp -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - mysql -hlocalhost --protocol=tcp -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -e "SELECT VERSION()"
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
