dist: trusty

sudo: required

language: go

go:
  - 1.10.x

env:
  - DB=mysql:5.7
  - DB=mysql:8.0

services:
  - docker

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - sudo service mysql stop
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT=127.0.0.1:3306
  - export MYSQL_PASSWORD=tests
  - ./.travis/install-and-init-db.sh
  - mysql -h127.0.0.1 -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
