dist: trusty
sudo: required
language: go
go:
  - 1.10.x
env:
  - DB=mysql VERSION=5.7
  - DB=mysql VERSION=8.0

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - sudo service mysql stop
  - docker run --rm --name mysql -e MYSQL_ROOT_PASSWORD=tests -d -p 127.0.0.1:3306:3306 ${DB}:${VERSION}
  - sleep 5
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT=127.0.0.1:3306
  - export MYSQL_PASSWORD=tests
  - mysql -h127.0.0.1 -uroot -ptests -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - mysql -h127.0.0.1 -uroot -ptests -e "SELECT VERSION()"
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
