dist: trusty

sudo: required

language: go

go:
  - 1.10.x

env:
  - DB=mysql:5.7
  - DB=mysql:8.0

services:
  - docker

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - sudo service mysql stop
  - export MYSQL_HOST=127.0.0.1
  - export MYSQL_PORT=3306
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT="${MYSQL_HOST}:${MYSQL_PORT}"
  - export MYSQL_PASSWORD=tests
  - docker pull $DB
  - docker run -d -p ${MYSQL_HOST}:${MYSQL_PORT}:${MYSQL_PORT} -e MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD} $DB
  - docker ps -a
  - mysqladmin  -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} ping --count=5 --sleep=5
  - mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
