dist: trusty

sudo: required

language: go

go:
  - 1.10.x

env:
  - DB=mysql:5.7
  - DB=mysql:8.0

services:
  - docker

script:
  - test -d /home/travis/gopath/src/github.com/terraform-providers || mv $(dirname $PWD) /home/travis/gopath/src/github.com/terraform-providers
  - make test
  - make vet
  - make website-test
  - sudo service mysql stop
  - export MYSQL_HOST=127.0.0.1
  - export MYSQL_PORT=3306
  - export MYSQL_USERNAME=root
  - export MYSQL_ENDPOINT="${MYSQL_HOST}:${MYSQL_PORT}"
  - export MYSQL_PASSWORD=''
  - docker pull $DB
  - docker run -d -p ${MYSQL_HOST}:${MYSQL_PORT}:${MYSQL_PORT} -e MYSQL_ALLOW_EMPTY_PASSWORD MYSQL_ROOT_PASSWORD=''
  - docker ps -a
#    while ! mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_USERNAME} -p${MYSQL_PASSWORD} -e 'SELECT 1' > /dev/null 2>&1; do
  - |
    while ! mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_USERNAME} -e 'SELECT 1'; do
      echo 'Waiting for MySQL...'
      sleep 1;
    done;
  - mysql -h${MYSQL_HOST} -P${MYSQL_PORT} -u${MYSQL_USERNAME} -e "INSTALL PLUGIN mysql_no_login SONAME 'mysql_no_login.so';"
  - make testacc

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
